---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: LokiSharp's Homelab
base: https://homepage.slk.moe/

# https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url
# Used by some browsers to determine the start page of the web application
startUrl: https://homepage.slk.moe/

language: zh

# Define shared API provider options and secrets here,
# You can then pass provider instead of apiKey in your widget configuration.
providers:
  # read api keys from environment variables
  openweathermap: { { HOMEPAGE_VAR_WEATHERAPI_APIKEY } }
  weatherapi: { { HOMEPAGE_VAR_WEATHERAPI_APIKEY } }

theme: dark # or light

# Supported colors are:
# slate, gray, zinc, neutral, stone, amber,
# yellow, lime, green, emerald, teal, cyan,
# sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
color: slate

# make all cards in a row the same height.
useEqualHeights: true

# Groups and its layout
# Groups Name should match the name defined in your services.yaml or widgets.yaml
layout:
  Homelab Monitoring:
    icon: mdi-monitor-dashboard
    initiallyCollapsed: false # collapsed by default
    tab: Main
    style: row
    columns: 3

  Homelab Applications:
    icon: si-homepage
    tab: Main

# https://gethomepage.dev/latest/configs/services/#icons
# iconStyle: theme # optional, defaults to gradient

# Typing in homepage to quick search
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

# Show docker stats
showStats: true

hideErrors: false
