---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
#
# Icons:

#   1. .png/.svg: will be referenced from https://github.com/walkxcode/dashboard-icons
#   2. mdi-XXX:   https://pictogrammers.com/library/mdi/
#   3. si-XXX:    https://simpleicons.org/
- Homelab Monitoring:
    - Grafana:
        icon: grafana.svg
        href: https://grafana.slk.moe
        description: Data visualised on dashboards
        siteMonitor: https://grafana.slk.moe
    - Prometheus Dashboard:
        icon: prometheus.svg
        href: https://prometheus.slk.moe
        description: Monitoring - Prometheus
        siteMonitor: https://prometheus.slk.moe

- Homelab Applications:
    - SFTPGO:
        icon: sftpgo.png
        href: "https://sftpgo.slk.moe/web/admin/folders"
        description: WebDAV & SFTP server
        siteMonitor: https://sftpgo.slk.moe/
    - MinIO:
        icon: minio.png
        href: "https://minio-ui.slk.moe/"
        description: S3 compatible object storage
        siteMonitor: "https://minio-ui.slk.moe/"
    - Gitea:
        icon: gitea.png
        href: "https://git.slk.moe/"
        description: Gitea - Git with a cup of tea
        siteMonitor: "https://git.slk.moe/"
