-- Shared Hyprland configuration.
-- Environment variables, monitor rules, and the systemd session hook are
-- generated by Home Manager before this file is appended.

hl.config({
  input = {
    kb_layout = "us",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",
    follow_mouse = 1,
    mouse_refocus = false,
    natural_scroll = false,
    force_no_accel = false,
    numlock_by_default = true,
    touchpad = {
      natural_scroll = true,
    },
  },
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 4,
    col = {
      active_border = "0xFFB4A1DB",
      inactive_border = "0xFF343A40",
    },
  },
  decoration = {
    rounding = 8,
    active_opacity = 1.0,
    inactive_opacity = 0.9,
    fullscreen_opacity = 1.0,
    blur = {
      enabled = true,
      size = 3,
      passes = 1,
      ignore_opacity = false,
    },
  },
  animations = {
    enabled = true,
  },
})

hl.animation({ leaf = "windows", enabled = true, speed = 8, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 8, bezier = "default" })

local floating_classes = {
  "^(foot-float)$",
  "^(yad|nm-connection-editor|pavucontrol)$",
  "^(xfce-polkit|kvantummanager|qt5ct)$",
  "^(feh|imv|Gpicview|Gimp|nomacs)$",
  "^(VirtualBox Manager|qemu|Qemu-system-x86_64)$",
  "^(xfce4-appfinder)$",
}

for _, class in ipairs(floating_classes) do
  hl.window_rule({ match = { class = class }, float = true })
end

hl.window_rule({
  match = { class = "^(foot-full)$" },
  float = true,
  move = { 0, 0 },
  size = { "100%", "100%" },
})

hl.window_rule({
  match = { class = "^(wlogout)$" },
  float = true,
  move = { 0, 0 },
  size = { "100%", "100%" },
  animation = "slide",
})

hl.window_rule({ match = { class = "^(fcitx)$" }, pseudo = true })

local term = "kitty"
local app_launcher = "~/.config/hypr/scripts/menu"
local volume = "~/.config/hypr/scripts/volume"
local backlight = "~/.config/hypr/scripts/brightness"
local lockscreen = "~/.config/hypr/scripts/lockscreen"
local logout_menu = "~/.config/hypr/scripts/wlogout"
local colorpicker = "~/.config/hypr/scripts/colorpicker"

hl.bind("SUPER + Return", hl.dsp.exec_cmd(term))
hl.bind("SUPER + D", hl.dsp.exec_cmd(app_launcher))

hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("CTRL + ALT + Delete", hl.dsp.exit())
hl.bind("SUPER + F", hl.dsp.window.fullscreen())
hl.bind("SUPER + Space", hl.dsp.window.float())
hl.bind("SUPER + S", hl.dsp.window.pseudo())

hl.bind("SUPER + N", hl.dsp.exec_cmd("nm-connection-editor"))
hl.bind("SUPER + P", hl.dsp.exec_cmd(colorpicker))
hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd(lockscreen))
hl.bind("SUPER + SHIFT + X", hl.dsp.exec_cmd(logout_menu))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(backlight .. " --inc"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(backlight .. " --dec"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(volume .. " --inc"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(volume .. " --dec"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(volume .. " --toggle"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(volume .. " --toggle-mic"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("mpc next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("mpc prev"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("mpc toggle"))
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("mpc stop"))

hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m output -o ~/Pictures/Screenshots -- imv"))
hl.bind("SUPER + Print", hl.dsp.exec_cmd("hyprshot -m window -o ~/Pictures/Screenshots -- imv"))
hl.bind(
  "CTRL + Print",
  hl.dsp.exec_cmd("XDG_CURRENT_DESKTOP=sway flameshot gui --raw -p ~/Pictures/Screenshots | wl-copy")
)

local directions = {
  left = "l",
  right = "r",
  up = "u",
  down = "d",
}

for key, direction in pairs(directions) do
  hl.bind("SUPER + " .. key, hl.dsp.focus({ direction = direction }))
  hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ direction = direction }))
end

local resize_steps = {
  left = { x = -20, y = 0 },
  right = { x = 20, y = 0 },
  up = { x = 0, y = -20 },
  down = { x = 0, y = 20 },
}

for key, step in pairs(resize_steps) do
  hl.bind(
    "SUPER + CTRL + " .. key,
    hl.dsp.window.resize({ x = step.x, y = step.y, relative = true })
  )
end

for workspace = 1, 10 do
  local key = workspace == 10 and "0" or tostring(workspace)
  hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = workspace }))
  hl.bind(
    "SUPER + SHIFT + " .. key,
    hl.dsp.window.move({ workspace = workspace, follow = false })
  )
end

hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.on("hyprland.start", function()
  hl.exec_cmd("~/.config/hypr/scripts/startup")
  hl.exec_cmd("cp ~/.config/fcitx5/profile-bak ~/.config/fcitx5/profile")
  hl.exec_cmd("fcitx5 -d --replace")
end)

hl.bind(
  "ALT + E",
  hl.dsp.exec_cmd("pkill fcitx5 -9; sleep 1; fcitx5 -d --replace; sleep 1; fcitx5-remote -r")
)
