{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.modules.base.hardening;
in
{
  config = mkIf (cfg.enable && cfg."stage-2".enable && config.services.caddy.enable) {
    security.apparmor.policies.caddy = {
      state = "complain";
      profile = ''
        #include <tunables/global>

        ${pkgs.caddy}/bin/caddy {
          #include <abstractions/base>
          #include <abstractions/nameservice>
          #include <abstractions/ssl_certs>

          capability net_bind_service,
          capability dac_override,

          network inet,
          network inet6,

          # Allow reading from nix store for configs and assets
          /nix/store/** r,

          # Read Caddyfile and other configs generated by Nix
          /etc/caddy/** r,

          # Caddy data directory (crucial for ACME certificates)
          /var/lib/caddy/** rwkl,

          # Allow execution of itself
          ${pkgs.caddy}/bin/caddy mr,
        }
      '';
    };
  };
}
