{ config
, mylib
, pkgs
, ...
}:
{
  config = mylib.apparmor.mkPolicy {
    inherit config;
    name = "caddy";
    enable = config.services.caddy.enable;
    profile = ''
      #include <tunables/global>

      ${pkgs.caddy}/bin/caddy flags=(attach_disconnected) {
        #include <abstractions/base>
        #include <abstractions/nameservice>
        #include <abstractions/ssl_certs>

        capability net_bind_service,
        capability dac_override,

        network inet,
        network inet6,
        network tcp,
        network udp,

        # Allow reading from nix store for configs and assets
        /nix/store/** r,
        /nix/store/** m,
        /nix/store/**/*.so* mr,
        /nix/store/**/lib/*.so* mr,

        # Read Caddyfile and other configs generated by Nix
        /etc/caddy/ r,
        /etc/caddy/** r,

        # systemd notify
        /run/systemd/notify w,

        # machine-id / runtime introspection
        /etc/machine-id r,
        /proc/self/cgroup r,
        /proc/self/mountinfo r,
        /proc/[0-9]*/cgroup r,
        /proc/[0-9]*/mountinfo r,
        /proc/sys/net/core/somaxconn r,

        # Caddy 会读取 cgroup 限制信息
        /sys/fs/cgroup/system.slice/caddy.service/cpu.max r,
        /sys/fs/cgroup/system.slice/caddy.service/memory.max r,
        /sys/fs/cgroup/system.slice/memory.max r,

        # Secrets
        /run/secrets/caddy-ecc-server.key r,
        /run/secrets.d/*/caddy-ecc-server.key r,

        # Caddy data / logs
        /var/lib/caddy/ rwkl,
        /var/lib/caddy/** rwkl,

        /data/apps/caddy/ rwkl,
        /data/apps/caddy/** rwkl,

        /var/log/caddy/ rwkl,
        /var/log/caddy/** rwkl,

        # Allow execution of itself
        ${pkgs.caddy}/bin/caddy mr,
      }
    '';
  };
}
