name: Nix Flake Eval Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Nix Flake Eval Tests
        run: |
          echo 'Flake Eval Tests'
          nix eval .#evalTests --show-trace --print-build-logs --verbose